<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['Afghanistan', 'AF'],
            ['Albania', 'AL'],
            ['Algeria', 'DZ'],
            ['Andorra', 'AD'],
            ['Angola', 'AO'],
            ['Antigua and Barbuda', 'AG'],
            ['Argentina', 'AR'],
            ['Armenia', 'AR'],
            ['Australia','AU'],
            ['Austria', 'AT'],
            ['Azerbaijan', 'AZ'],
            ['Bahamas','BS'],
            ['Bahrain', 'BH'],
            ['Bangladesh', 'BD'],
            ['Barbados', 'BB'],
            ['Belarus', 'BY'],
            ['Belgium', 'BE'],
            ['Belize', 'BZ'],
            ['Benin', 'BJ'],
            ['Bhutan', 'BT'],
            ['Bolivia', 'BO'],
            ['Bosnia and Herzegovina', 'BA'],
            ['Botswana', 'BW'],
            ['Brazil','BR'],
            ['Brunei','BN'],
            ['Bulgaria', 'BG'],
            ['Burkina Faso','BF'],
            ['Burundi', 'BI'],
            ['Cambodia', 'KH'],
            ['Cameroon', 'CM'],
            ['Canada', 'CA'],
            ['Central African Republic', 'CF'],
            ['Chad','td'],
            ['Chile', 'CL'],
            ['China', 'CN'],
            ['Colombia', 'CO'],
            ['Comoros', 'KM'],
            ['Congo (Brazzaville', 'CG'],
            ['Congo (Kinshasa)', 'CD'],
            ['Costa Rica', 'CR'],
            ["Cote d'lvoire", 'CL'],
            ['Croatia', 'HR'],
            ['Cuba', 'CU'],
            ['Cyprus', 'CY'],
            ['Czech Republic', 'CZ'],
            ['Denmark', 'DK'],
            ['Djibouti', 'DJ'],
            ['Dominica', 'DM'],
            ['Dominican Republic', 'DO'],
            ['Ecuador', 'EC'],
            ['Egypt', 'EG'],
            ['El Salvador','SV'],
            ['Equatorial Guinea', 'GQ'],
            ['Eritrea', 'ER'],
            ['Estonia', 'EE'],
            ['Ethiopia','ET'],
            ['Fiji','FJ'],
            ['Finland','FI'],
            ['France','FR'],
            ['Gabon','GA'],
            ['Gambia','GM'],
            ['Georgia','GE'],
            ['Germany','DE'],
            ['Ghana','GH'],
            ['Greece','GR'],
            ['Grenada','GD'],
            ['Guatemala','GT'],
            ['Guinea','GN'],
            ['Guinea-Bissau','GW'],
            ['Guyana','GY'],
            ['Haiti','HT'],
            ['Honduras','HN'],
            ['Hungary','HU'],
            ['Iceland','IS'],
            ['India','IN'],
            ['Indonesia','ID'],
            ['Iran','IR'],
            ['Iraq','IQ'],
            ['Ireland','IE'],
            ['Italy','IT'],
            ['Jamaica','JM'],
            ['Japan','JP'],
            ['Jordan','JO'],
            ['Kazakhstan','KZ'],
            ['Kenya','KE'],
            ['Kiribati','KI'],
            ['North Korea','KP'],
            ['South Korea','KR'],
            ['Kosovo','XK'],
            ['Kuwait','KW'],
            ['Kyrgyzstan','KG'],
            ['Laos','LA'],
            ['Latvia','LV'],
            ['Lebanon','LB'],
            ['Lesotho','LS'],
            ['Liberia','LR'],
            ['Libya','LY'],
            ['Liechtenstein','LI'],
            ['Lithuania','LT'],
            ['Luxembourg','LU'],
            ['Macedonia (FYROM)','MK'],
            ['Madagascar','MG'],
            ['Malawi','MW'],
            ['Malaysia','MY'],
            ['Maldives','MV'],
            ['Mali','ML'],
            ['Malta','MT'],
            ['Marshall Islands','MH'],
            ['Mauritania','MR'],
            ['Mauritius','MU'],
            ['Mexico', 'MX'],
            ['Micronesia','FM'],
            ['Moldova','MD'],
            ['Monaco', 'MC'],
            ['Mongolia','MN'],
            ['Montenegro','ME'],
            ['Morocco','MA'],
            ['Mozambique','MZ'],
            ['Myanmar (Burma)','MM'],
            ['Namibia','NA'],
            ['Nauru','NR'],
            ['Nepal','NP'],
            ['Netherlands','NL'],
            ['New Zealand','NZ'],
            ['Nicaragua','NI'],
            ['Niger','NE'],
            ['Nigeria','NG'],
            ['Norway','NO'],
            ['Oman','OM'],
            ['Pakistan','PK'],
            ['Palau','PW'],
            ['Panama','PA'],
            ['Papua New Guinea','PG'],
            ['Paraguay','PY'],
            ['Peru','PE'],
            ['Philippines','PH'],
            ['Poland','PL'],
            ['Portugal','PT'],
            ['Qatar','QA'],
            ['Romania','RO'],
            ['Russia','RU'],
            ['Rwanda','RW'],
            ['Saint Kitts and Nevis','KN'],
            ['Saint Lucia','LC'],
            ['Saint Vincent and the Grenadines','VC'],
            ['Samoa','WS'],
            ['San Marino','SM'],
        ];

        foreach($countries as $country){
            Country::create([
                'name' => $country[0],
                'code' => $country[1],
            ]);
        }
    }
}
